export const HomeDescription = {
    title: 'Home Page',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent arcu diam, dignissim non pharetra id, molestie et nisi. Ut lacinia et nunc ac imperdiet. Nullam porttitor dui id posuere accumsan. Aliquam suscipit quam a enim consectetur rutrum. Sed laoreet nibh eget ultricies gravida. Nulla nec mattis nunc, nec porta massa. In vitae feugiat quam, et accumsan enim. Nunc dignissim dui eget sem bibendum sollicitudin. Fusce et tellus magna. Vestibulum magna orci, euismod vel nunc vel, laoreet convallis quam. Nullam semper lorem quis ante porta, et lobortis lacus accumsan. Morbi pellentesque est et iaculis faucibus. Proin in aliquam augue.\n' +
        '\n' +
        'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam augue elit, molestie in suscipit nec, interdum id quam. Sed sit amet est id augue bibendum rutrum eget a purus. Integer faucibus, libero in iaculis maximus, velit velit sagittis mi, ac feugiat felis mauris vitae turpis. Vestibulum eleifend, libero sed consequat ultrices, nisi lorem auctor est, in pretium libero lorem eu nisl. Sed dictum velit sit amet elit auctor aliquet. Mauris non ultricies massa. Ut arcu enim, malesuada ut suscipit commodo, ornare eu ex. Quisque nec maximus purus. Aliquam hendrerit finibus odio eu porta. Phasellus a ornare tellus, sit amet rhoncus mauris. Cras condimentum condimentum sollicitudin.\n' +
        '\n' +
        'Aenean non porttitor libero, eget molestie lacus. Maecenas vitae tincidunt odio. Ut lacus turpis, condimentum in elementum quis, dapibus ac metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ut dignissim enim. Curabitur quis metus nec eros eleifend iaculis. Duis a nisi at dolor interdum sagittis.\n' +
        '\n' +
        'Nulla sed tellus et risus placerat sollicitudin. Phasellus feugiat felis non metus mattis, eu hendrerit diam sagittis. Etiam suscipit tincidunt scelerisque. Proin quis diam at tortor viverra lobortis. Vestibulum posuere urna ut sodales volutpat. Nam sollicitudin lectus nec convallis posuere. Suspendisse commodo augue id aliquet interdum. Sed a augue eu dui egestas dapibus. Praesent turpis quam, congue ut fermentum id, lobortis nec velit. Donec pulvinar, eros quis fringilla semper, sem odio aliquet lectus, non posuere odio ex in velit.\n' +
        '\n' +
        'Quisque sem purus, sollicitudin at volutpat consequat, consequat eu mauris. Nullam vestibulum accumsan purus. Ut nec mattis odio, nec maximus metus. Aliquam sollicitudin vehicula mi, id fringilla erat egestas ac. Pellentesque placerat leo eget blandit tincidunt. Phasellus viverra tincidunt ornare. Nam non libero id metus finibus accumsan sed quis tortor. Sed commodo ipsum eu nisl pharetra, quis ultrices nibh scelerisque. Proin eu lectus vel ante pulvinar placerat quis at tellus. Duis eget ligula nulla. Cras ac ultrices ante.\n' +
        '\n' +
        'Donec laoreet mi sed lobortis eleifend. Etiam ac fringilla urna, a maximus enim. Phasellus sit amet dapibus neque, vitae malesuada odio. Pellentesque at luctus diam. Sed pulvinar faucibus pretium. Duis sem lorem, sagittis nec enim sit amet, laoreet luctus velit. Mauris eleifend augue ut sem tempor, at egestas dolor consectetur. Aenean diam magna, feugiat eget lorem ac, fringilla pretium libero. Vivamus id consectetur enim.\n' +
        '\n' +
        'In lobortis lacus a mauris faucibus dignissim. Nunc in ante vitae neque semper consequat. Aenean nec eleifend elit. Praesent condimentum risus sit amet lacus fringilla, vitae egestas libero efficitur. Etiam feugiat eleifend justo, vel vestibulum nunc convallis in. Maecenas id sodales purus, nec semper sem. Pellentesque elementum tempus nisl ac condimentum. Nulla nec eros auctor, varius tellus eu, molestie mi. Aliquam mattis massa at fringilla pellentesque. Nunc vestibulum laoreet feugiat. Sed a eros lacus.\n' +
        '\n' +
        'Vivamus porttitor orci est, pulvinar semper mi placerat at. In ultricies fermentum sapien id accumsan. Proin blandit dignissim purus sit amet molestie. Etiam arcu justo, pellentesque ac nibh eget, eleifend porttitor enim. Vivamus vel hendrerit nibh. Mauris in egestas libero, at luctus neque. Vestibulum tellus purus, rhoncus eget commodo sed, aliquam et est.\n' +
        '\n' +
        'Donec elementum quam sed porta vehicula. Sed scelerisque tortor et viverra convallis. Etiam interdum tempus volutpat. Suspendisse dui mi, interdum suscipit magna in, pellentesque rhoncus sapien. Mauris condimentum scelerisque nibh eu dignissim. Nullam sit amet eros ut urna ultricies dignissim non commodo lacus. Pellentesque non nibh faucibus lectus placerat egestas. Nullam tempus sem orci, ut tempor neque condimentum non. Vivamus sed mattis lectus. Morbi rutrum magna sit amet tellus tincidunt condimentum. Ut sit amet maximus arcu, sit amet bibendum mi. Quisque malesuada feugiat nulla, sit amet malesuada nunc volutpat nec.\n' +
        '\n' +
        'Vivamus rhoncus nulla ut leo consequat pretium. Nulla cursus libero in orci vehicula, et gravida orci vestibulum. Proin tortor felis, semper ut nisl et, euismod egestas eros. Integer nisl ipsum, convallis at aliquet at, hendrerit vitae velit. Suspendisse venenatis, purus ornare finibus pulvinar, ex mauris sollicitudin lorem, in lobortis sem magna ut sapien. Praesent diam lectus, venenatis at feugiat at, porta at mi. Pellentesque a orci sit amet eros volutpat rutrum. Sed ultrices consectetur augue, nec tempor magna porttitor at. Sed nisi nulla, posuere molestie orci a, malesuada condimentum felis. Maecenas libero tellus, pellentesque eu gravida vitae, volutpat vel libero. Aenean lacinia velit vel justo efficitur molestie. Sed euismod mi odio, a pretium risus pulvinar molestie. Cras fringilla consectetur viverra. Curabitur non ex tempor, maximus ante volutpat, elementum felis.',
}